config/routes.rb
Rails.application.routes.draw do
  get 'personaldata/index'
  get 'test_task/index'
  get 'profilevisitor/index'
  devise_for :usernames
  get 'profile', to: 'profile#index'
  get 'profilevisitor', to: 'profilevisitor#index'
  get 'test_task', to: 'test_task#index'
  get 'personaldata', to: 'personaldata#index'
  get 'links', to: 'links#index'


  resources :taskforms do
    resources :issues
    resources :youanswers
    resources :accepts
  end
  devise_for :users
  #resources :topics
  resources :visitors
  resources :statisticscreators
  resources :statisticvisitors
  resources :contacts
  resources :linktasks
  resources :topics do
    get :view, on: :member
    resources :questions
    resources :answers
    resources :consents
    resources :passwords
    resources :usertabls
    resources :settings
  end
  resources :creators
  get 'welcome/index'

  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/visitor.rb
class Visitor < ApplicationRecord
  validates :photo, file_size: { less_than: 1.megabytes }
  mount_uploader :photo, ImageUploader
  validates :name, length: { in: 2..25 }, format: { with: /\A[А-Я][а-яё]+\z/}, presence: true
  validates :surname, length: { in: 3..25 }, format: { with: /\A[А-Я][а-яё]+\z/}, presence: true
  validates :telephone, length: { in: 3..25 }, format: { with: /\A[0-9\s+-]+\z/}, presence: true
  validates :birthdate, presence: true
  validates :country, format: { with: /\A[А-Я][а-яё]+\z/}, presence: true
  validates :city, format: { with: /\A[А-Я][а-яё]+\z/}, presence: true
  validates :idregvis, presence: true
  validates :sex, presence: true
  validates :promocode, length: { in: 3..300 }, allow_blank: true
  validates :codevisitor, presence: true


  private

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  before_action :authenticate_username!
  before_action :visitor_find, only: [:show, :edit, :update, :destroy]
  after_action :visitor_delete, only: [:edit]

  def index
    @visitors  = Visitor.all
    redirect_to '/visitors/new'
  end

  def show
    redirect_to '/profilevisitor/'
  end

  def new
      @visitor = Visitor.new
  end

  def edit
  end

  def create
      @visitor = Visitor.new(visitor_params)

      if @visitor.save
      redirect_to @visitor
    else
      render 'new'
    end
  end

  def update
    if @visitor.update(visitor_params)
      redirect_to '/profilevisitor/'
    else
      render 'edit'
    end
  end

  def destroy
    @visitor.destroy
    redirect_to '/topics/'
  end

  private

  def visitor_delete
    val1 = ["visitor_surname", "visitor_name", "visitor_telephone", "visitor_sex"]
    val2 = ["visitor_age", "visitor_country", "visitor_city"]
    val = val1 + val2
    val.each do |value|
      $visitor_name.del value + current_username.id.to_s
    end
  end

  def visitor_find
    @visitor = Visitor.find(params[:id])
  end

  def visitor_params
    params.require(:visitor).permit(:name, :surname, :telephone, :birthdate,
        :photo, :promocode, :country, :city, :idregvis, :sex, :codevisitor)
  end
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/visitors/edit.html.erb
<% if (username_signed_in?) %><% userid = current_username.id %>
  <div class="container">
    <h1>Редактировать личные данные</h1>
    <%= form_with model: @visitor, url: visitor_path, local: true do |form|  %>
      <% if @visitor.errors.any? %>
        <div id="error_explanation">
          <h2>
            <% er=@visitor.errors.count %>
            <% if er>0 %>
              <span class="formerrors">Форма заполнена неправильно</span>
            <% end %>
          </h2>
            <% if @visitor.errors[:photo] %>
              <p>Проверьте загружаемое изображение, размер файла не должен быть больше 1 Мб. Для загрузки используйте изображения в фомате .png, .jpg и .gif. </p>
            <% end %>
        </div>
      <% end %>
      <% if Visitor.find_by(idregvis: userid).photo.url(:thumb) !="" %>
        <%= image_tag Visitor.find_by(idregvis: userid).photo.url(:thumb), class: "photoprofile" %>
      <% end %>
      <p class="inputphotocreator">
        <%= form.file_field :photo %>
      </p>
      <hr>
      <div class="row">
        <div class="form-group col-lg-6 col-sm-12">
          <%= form.label :name, "Имя" %><br>
          <%= form.text_field :name, class: "w100" %>
        </div>
        <div class="form-group col-lg-6 col-sm-12">
          <%= form.label :surname, "Фамилия" %><br>
          <%= form.text_field :surname, class: "w100" %>
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="form-group col-lg-4 col-sm-12">
          <%= form.label :sex, "Пол" %><br>
          <%= form.select(:sex, [['Муж.', "Муж."], ['Жен.', "Жен."]]) %>
        </div>
        <div class="form-group col-lg-4 col-sm-12">
          <%= form.label :telephone, "Телефон" %><br>
          <%= form.text_field :telephone, class: "w100" %>
        </div>
        <div class="form-group col-lg-4 col-sm-12">
          <%= form.label :country, "Страна" %><br>
          <%= form.text_field :country, class: "w100" %>
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="form-group col-lg-4 col-sm-12">
          <%= form.label :city, "Город" %><br>
          <%= form.text_field :city, class: "w100" %>
        </div>
        <div class="form-group col-lg-4 col-sm-12">
          <%= form.label :birthdate, "Дата рождения" %><br>
          <%= form.date_field :birthdate, class: "w100" %>
        </div>
        <div class="form-group col-lg-4 col-sm-12">
          <%= form.label :promocode, "Промокод" %><br>
          <%= form.text_field :promocode, class: "w100" %>
        </div>
      </div>
      <hr>
      <%= form.hidden_field :idregvis, value: current_username.id %>
      <%= form.hidden_field :codevisitor, value: current_username.encrypted_password %>
      <p>
        <%= form.submit "Сохранить", class: "topic_button btn btn-primary" %>
      </p>
    <% end %>
    <p><a href="/profilevisitor/">Назад</a></p>
  </div>
  <% rr = Dir.children("public/uploads/tmp/")%>
  <% contrr = rr.count %>
  <% contrr = (contrr-1)%>
  <% for i in 0..contrr %>
    <% x = Dir.children("public/uploads/tmp/#{rr[i]}")%>
    <% x.each do |name| %>
      <% File.delete("public/uploads/tmp/#{rr[i]}/#{name}") %>
    <% end %>
  <% end %>
  <% rr.each do |namef| %>
    <% if Dir.empty?("public/uploads/tmp/#{namef}")%>
      <% Dir.delete("public/uploads/tmp/#{namef}") %>
    <% end %>
  <% end %>
<% end %>

app/views/visitors/index.html.erb
<% @visitors.each do |c| %>
  <% if c.photo !="" %>
    <img src="<%= c.photo.url(:thumb) %>">
  <% end %>
  <p><%= c.name %></p>
  <p><%= c.surname %></p>
  <p><%= c.telephone %></p>
  <p><%= c.birthdate %></p>
  <p><%= c.country %></p>
  <p><%= c.city %></p>
  <p><%= c.promocode %></p>
  <p><%= c.idregvis %></p>
  <hr>
<% end %>
<% #Creator.destroy_by(namecreator: "Александр") %>

app/views/visitors/new.html.erb
<% if (username_signed_in?) %><% useridname = current_username.id %>
  <% if Visitor.find_by(idregvis: useridname) %>
    <h2><%= Visitor.find_by(idreg: useridname).name %>, вы уже добавили данные</h2>
    <p>Для просмотра информации нажмите вкладку "Профиль".</p>
  <% else %>
    <h1>Добавить личные данные</h1>
    <div class="formswrapper">
      <%= form_with scope: :visitor, html: { multipart:  true }, url: visitors_path, local: true do |form| %>
      <% if @visitor.errors.any? %>
        <div id="error_explanation">
          <h2>
            <% er = @visitor.errors.count %>
            <% if er>0 %>
              <span class="formerrors">Форма заполнена неправильно</span>
            <% end %>
          </h2>
        </div>
      <% end %>
        <div class="row">
          <div class="form-group col-lg-4 col-sm-12">
            <%= form.label :photo, "Аватарка" %><br>
            <%= form.file_field :photo %>
          </div>
          <div class="form-group col-lg-4 col-sm-12">
            <%= form.label :name, "Имя*" %><br>
            <%= form.text_field :name, class: "w100" %>
          </div>
          <div class="form-group col-lg-4 col-sm-12">
            <%= form.label :surname, "Фамилия*" %><br>

            <%= form.text_field :surname, class: "w100" %>
          </div>
        </div>
        <hr>
        <div class="row">
          <div class="form-group col-lg-4 col-sm-12">
            <%= form.label :birthdate, "Дата рождения*" %><br>
            <%= form.date_field :birthdate, class: "w100" %>
          </div>
          <div class="form-group col-lg-4 col-sm-12">
            <%= form.label :sex, "Пол*" %><br>
            <%= form.select(:sex, [['Муж.', "Муж."], ['Жен.', "Жен."]]) %>
          </div>
          <div class="form-group col-lg-4 col-sm-12">
            <%= form.label :telephone, "Телефон*" %><br>
            <%= form.text_field :telephone, class: "w100" %>
            <small class="form-text text-muted">Пример: +7 900-000-00-00</small>
          </div>
        </div>
        <hr>
        <div class="row">
          <div class="form-group col-lg-4 col-sm-12">
            <%= form.label :country, "Страна*" %><br>
            <%= form.text_field :country, class: "w100" %>
          </div>
          <div class="form-group col-lg-4 col-sm-12">
            <%= form.label :city, "Город*" %><br>
            <%= form.text_field :city, class: "w100" %>
          </div>
          <div class="form-group col-lg-4 col-sm-12">
            <%= form.label :promocode, "Промокод" %><br>
            <%= form.text_field :promocode, class: "w100" %>
          </div>
        </div>
        <hr>
        <input type="hidden" name="visitor[idregvis]" id="visitor_idregvis" value="<% if (username_signed_in?) %><%= current_username.id %><% end %>">
        <%= form.hidden_field :idregvis, value: current_username.id %>
        <%= form.hidden_field :codevisitor, value: current_username.encrypted_password %>
        <p>
          <%= form.submit "Сохранить", class: "topic_button btn btn-primary" %>
        </p>
      <% end %>
    </div>
    <div class="notation">
      <p>Все поля с пометкой (*) должны быть заполнены.</p>
      <p>Предоставляя свои персональные данные Пользователь даёт согласие на обработку, хранение и использование своих персональных данных. <%= link_to "Подробнее", personaldata_path %></p>
    </div>
  <% end %>
<% end %>

app/views/visitors/show.html.erb
<div class="container">
  <% if (username_signed_in?) %><% userid = current_username.id %><% end %>
  <% if Visitor.find_by(idregvis: userid) !="" %>
    <h1>Профиль пользователя</h1>
    <%= image_tag @visitor.photo.url(:thumb), class: "photoprofile" if @visitor.photo?%>
    <h4><%= @visitor.surname %> <%= @visitor.name %> (<%= @visitor.telephone %>)</h4>
    <p>
      <strong>Email:</strong>
      <% if (username_signed_in?) %><%= current_username.email %><% end %>
    </p>
    <p>
      <strong>Id пользователя:</strong>
      <% if (username_signed_in?) %><%= current_username.id %><% end %>
    </p>
    <p>
      <strong>Зарегистрирован:</strong>
      <% if (username_signed_in?) %><% regdata = current_username.created_at %>
        <%= regdata.time.strftime("%d-%m-%Y") %>
      <% end %>
    </p>
    <% if @visitor.birthdate !="" %>
      <% birthdate = @visitor.birthdate %>
      <% birthdate.time.strftime("%d-%m-%Y") %>
    <p>
      <strong>Возраст:</strong>
      <% timed=Time.now.strftime("%d-%m-%Y") %>
      <% age = Time.diff(Time.now, birthdate) %>
      <%= age[:year] %> лет
    </p>
    <p>
      <strong>Пол:</strong>
      <%= @visitor.sex %>
    </p>
    <% end %>
    <% if @visitor.country !="" %>
      <p>
        <strong>Страна:</strong>
        <%= @visitor.country %>
      </p>
    <% end %>
    <% if @visitor.country !="" %>
      <p>
        <strong>Город:</strong>
        <%= @visitor.city %>
      </p>
    <% end %>
    <% if @visitor.promocode !="" %>
      <p>
        <strong>Промокод:</strong>
        <%= @visitor.promocode %>
      </p>
    <% end %>
  <% end %>
  <p><a href="/visitors/<%= Visitor.find_by(idregvis: userid).id %>/edit">Редактировать</a></p>
</div>