config/routes.rb
Rails.application.routes.draw do
  get 'personaldata/index'
  get 'test_task/index'
  get 'profilevisitor/index'
  devise_for :usernames
  get 'profile', to: 'profile#index'
  get 'profilevisitor', to: 'profilevisitor#index'
  get 'test_task', to: 'test_task#index'
  get 'personaldata', to: 'personaldata#index'
  get 'links', to: 'links#index'


  resources :taskforms do
    resources :issues
    resources :youanswers
    resources :accepts
  end
  devise_for :users
  #resources :topics
  resources :visitors
  resources :statisticscreators
  resources :statisticvisitors
  resources :contacts
  resources :linktasks
  resources :topics do
    get :view, on: :member
    resources :questions
    resources :answers
    resources :consents
    resources :passwords
    resources :usertabls
    resources :settings
  end
  resources :creators
  get 'welcome/index'

  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/topic.rb
class Topic < ApplicationRecord
  paginates_per  5
  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :consents, dependent: :destroy
  has_many :passwords, dependent: :destroy
  has_many :usertabls, dependent: :destroy
  has_many :settings, dependent: :destroy
  validates :titletopic, presence: true,
                    length: { in: 3..300 },
                    uniqueness: {scope: :idreg}


  validates :countquestions, numericality: true, presence: true,
                    length: { in: 1..3 }
  validates :sucquest, numericality: true, presence: true,
                    length: { in: 1..3 }
  validates :timetask, presence: true
  validates :intdate1, presence: true
  validates :password, length: { in: 3..20 }, allow_blank: true
  validates :idreg, numericality: true, presence: true, if: :user_validation?
  validates :successmessage, length: { in: 3..300 }, allow_blank: true
  validates :failuremessage, length: { in: 3..300 }, allow_blank: true
  validates :activ, length: { in: 3..5 }, presence: true
  validates :rand, length: { in: 3..5 }, presence: true
  validates :codecreator, presence: true

  private
    def user_validation?
      if User.find_by(id: self.idreg)
        if User.find_by(id: self.idreg).encrypted_password != self.codecreator
          errors.add(:idreg, "Ошибка")
        end
      else
        errors.add(:idreg, "Ошибка")
      end

      if User.find_by(encrypted_password: self.codecreator)
        if User.find_by(encrypted_password: self.codecreator).id != self.idreg
          errors.add(:idreg, "Ошибка")
        end
      else
        errors.add(:idreg, "Ошибка")
      end
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!
  before_action :topic_find, only: [:show, :view, :edit, :update, :destroy]
  after_action :statistica_creator, only: [:create, :update, :destroy]
  after_action :topic_id_link_delete, only: [:destroy]

  def index
    user = current_user.encrypted_password
    @topics = Topic.where(codecreator: user).order(id: :desc).page(params[:page])
  end

  def show
  end

  def view
  end

  def new
    @topic = Topic.new
    $compare_password = Redis.new
  end

  def edit
  end

  def create
    @topic = Topic.new(topic_params)
    if @topic.save
      redirect_to '/topics/'
    else
      render 'new'
    end
  end

  def update
    if @topic.update(topic_params)
      redirect_to @topic
    else
      render 'edit'
    end
  end

  def destroy
    @topic.destroy
    redirect_back(fallback_location: root_path)
  end

  private

  def topic_find
    @topic = Topic.find(params[:id])
  end

  def topic_id_link_delete
    @linktask = Linktask.all
    @linktask.each do |link|
      unless Topic.find_by(id: link.topicid)
        link.destroy
      end
    end
  end

  def statistica_creator
    userencrypted = current_user.encrypted_password
    all_test_array = ["all_test_tesk", "all_test_tesk_activ", "all_test_tesk_stop"]
    all_test_array.each do |all_test_array|
      if $all_task_creat
        if $all_task_creat.get userencrypted + all_test_array
          $all_task_creat.del userencrypted + all_test_array
        end
      end
    end
  end

  def topic_params
      params.require(:topic).permit(:titletopic, :idreg, :codecreator, :countquestions, :sucquest, :timetask, :password, :ip, :email, :successmessage, :typetopic, :activ, :failuremessage, :intdate1, :intdate2, :rand)
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_show_creator.html.erb
<h1>
  Тестовое задание "<a href="/topics/<%= @topic.id %>/edit"><%= @topic.titletopic %></a>"
</h1>
<div class="row">
  <div class="col-lg-6">
    <table class="borderdiv">
      <tr>
        <td colspan="2">
          <h4>Вопросов в тесте: <a href="/topics/<%= @topic.id %>/edit"><%= @topic.countquestions %></a></h4>
        </td>
      </tr>
      <tr>
        <td colspan="2"><p>Указано количество вопросов в тестовом задании. Если вы добавили меньше вопросов, чем
          указано, то ваше задание будет неактивно.</p></td>
      </tr>
    </table>
  </div>
  <div class="col-lg-6">
    <table class="borderdiv">
      <tr>
        <td colspan="2">
          <h4>Правильных ответов: <a href="/topics/<%= @topic.id %>/edit"><%= @topic.sucquest %></a></h4></td>
      </tr>
      <tr>
        <td colspan="2"><p>Если по итогам прохождения теста, количество правильных ответов равно или больше, чем указано,
          то задание считается пройденым.</p></td>
      </tr>
    </table>
  </div>
</div>
<div class="row">
  <div class="col-lg-6">
    <table class="borderdiv">
      <tr>
        <td><h4>Успешное сообщение:</h4></td>
      </tr>
      <tr>
        <td><p><a href="/topics/<%= @topic.id %>/edit"><%= @topic.successmessage %></a></p></td>
      </tr>
    </table>
  </div>
  <div class="col-lg-6">
    <table class="borderdiv">
      <tr>
        <td><h4>Неудовлетвори&shy;тель&shy;ное сообщение:</h4></td>
      </tr>
      <tr>
        <td><p><a href="/topics/<%= @topic.id %>/edit"><%= @topic.failuremessage %></a></p></td>
      </tr>
    </table>
  </div>
</div>
<div class="row">
  <div class="col-lg-6">
    <table class="borderdiv">
      <tr>
        <td><h4>Начало показов:</h4></td>
      </tr>
      <tr>
        <td><p><a href="/topics/<%= @topic.id %>/edit"><%= @topic.intdate1.strftime("%d.%m.%Y %H:%M") %></a></p></td>
      </tr>
    </table>
  </div>
  <div class="col-lg-6">
    <table class="borderdiv">
      <tr>
        <td><h4>Окончание показов:</h4></td>
      </tr>
      <tr>
        <td>
          <p>
            <% if @topic.intdate2 %>
              <a href="/topics/<%= @topic.id %>/edit"><%= @topic.intdate2.strftime("%d.%m.%Y %H:%M") %></a>
            <% else %>
              <a href="/topics/<%= @topic.id %>/edit">Не задано</a>
            <% end %>
          </p>
        </td>
      </tr>
    </table>
  </div>
</div>
<div class="row">
  <div class="col-lg-3">
    <table class="borderdiv">
      <tr>
        <td><h4>Время:</h4></td>
      </tr>
      <tr>
        <td>
          <h5>
            <% @topic.timetask %>
            <% date=@topic.timetask %>
            <a href="/topics/<%= @topic.id %>/edit"><%= date.strftime("%H:%M")%></a>
          </h5>
        </td>
      </tr>
    </table>
  </div>
  <div class="col-lg-3">
    <table class="borderdiv">
      <tr>
        <td><h4>Показы:</h4></td>
      </tr>
      <tr>
        <td><h5><a href="/topics/<%= @topic.id %>/edit"><%= @topic.activ %></a></h5></td>
      </tr>
    </table>
  </div>
  <div class="col-lg-3">
    <table class="borderdiv">
      <tr>
        <td><h4>Случай&shy;ный поря&shy;док:</h4></td>
      </tr>
      <tr>
        <td><h5><a href="/topics/<%= @topic.id %>/edit"><%= @topic.rand %></a></h5></td>
      </tr>
    </table>
  </div>
  <div class="col-lg-3">
    <table class="borderdiv">
      <tr>
        <td><h4>Пароль:</h4></td>
      </tr>
      <tr>
        <td>
          <h5>
            <a href="/topics/<%= @topic.id %>/edit"><%= @topic.password %></a>
          </h5>
        </td>
      </tr>
    </table>
  </div>
</div>
<%= link_to 'Редактировать', edit_topic_path(@topic) %> |
<%= link_to 'Назад', topics_path %>

app/views/topics/edit.html.erb
<% if (user_signed_in?) %><% idreg1 = current_user.id %><% end %>
  <% if Topic.find_by(idreg: idreg1) %>
    <% curentdate = Time.new %>
    <% newcurentdate = curentdate.strftime("%Y-%m-%dT%H:%M") %>
    <h1>Редактировать</h1>
    <%= form_with(model: @topic, local: true) do |form| %>
      <% if @topic.errors.any? %>
        <div id="error_explanation">
          <h2>
            <% er = @topic.errors.count %>
            <% if er > 0 %>
              <span>Форма заполнена неправильно</span>
            <% end %>
          </h2>
        </div>
      <% end %>
  <div class="row">
    <div class="col-lg-12">
      <table class="borderdiv">
        <tr>
          <td><h4>Название:</h4></td>
        </tr>
        <tr>
          <td><textarea name="topic[titletopic]" id="topic_titletopic" class="w100"><%= @topic.titletopic %></textarea></td>
        </tr>

      </table>
    </div>
  </div>
<div class="row">
  <div class="col-lg-6">
    <table class="borderdiv">
      <tr>
        <td colspan="2"><h4>Вопросов в тесте:</h4></td>
        </tr>
        <tr>
        <td colspan="2">
          <h4>
            <% if @topic.countquestions %>
              <input id="topic_countquestions" class="w100" max="100" min="1" name="topic[countquestions]" step="1" type="number" value=<%= @topic.countquestions %> />
            <% else %>
              <input id="topic_countquestions" class="w100" max="100" min="1" name="topic[countquestions]" step="1" type="number" value="10" />
            <% end %>
          </h4>
        </td>
      </tr>
      <tr>
        <td colspan="2">
          <p>Указано количество вопросов в тестовом задании. Если вы добавили меньше вопросов, чем
          указано, то ваше задание будет неактивно.</p>
        </td>
      </tr>
    </table>
  </div>
  <div class="col-lg-6">
    <table class="borderdiv">
      <tr>
        <td colspan="2"><h4>Правильных ответов:</h4></td>
      </tr>
      <tr>
      <td colspan="2">
        <h4>
          <% if @topic.sucquest %>
            <input id="topic_sucquest" class="w100" max="100" min="1" name="topic[sucquest]" step="1" type="number" value=<%= @topic.sucquest %> />
          <% else %>
            <input id="topic_sucquest" class="w100" max="100" min="1" name="topic[sucquest]" step="1" type="number" value="5" />
          <% end %>
        </h4>
      </td>
    </tr>
      <tr>
        <td colspan="2">
          <p>Если по итогам прохождения теста, количество правильных ответов равно или больше, чем указано,
          то задание считается пройденым.</p>
        </td>
      </tr>
    </table>
  </div>
</div>
<div class="row">
  <div class="col-lg-6">
    <table class="borderdiv">
      <tr>
        <td><h4>Успешное сообщение:</h4></td>
      </tr>
      <tr>
        <td>
          <p>
            <% if @topic.successmessage %>
              <textarea name="topic[successmessage]" id="topic_successmessage" class="w100"><%= @topic.successmessage %></textarea>
            <% else %>
              <textarea name="topic[successmessage]" id="topic_successmessage" class="w100">Вы успешно прошли тест</textarea>
            <% end %>
          </p>
        </td>
      </tr>
    </table>
  </div>
  <div class="col-lg-6">
    <table class="borderdiv">
      <tr>
        <td><h4>Неудовлетвори&shy;тель&shy;ное сообщение:</h4></td>
      </tr>
      <tr>
        <td>
          <p>
            <% if @topic.failuremessage %>
              <textarea name="topic[failuremessage]" id="failuremessage_successmessage" class="w100"><%= @topic.failuremessage %></textarea>
            <% else %>
              <textarea name="topic[failuremessage]" id="failuremessage_successmessage" class="w100">Вы не прошли тест</textarea>
            <% end %>
          </p>
        </td>
      </tr>
    </table>
  </div>
</div>
<div class="row">
  <div class="col-lg-6">
    <table class="borderdiv">
      <tr>
        <td><h4>Начало показов:</h4></td>
      </tr>
      <tr>
        <td>
          <p>
            <% if @topic.intdate1 %>
              <%= form.datetime_local_field :intdate1, class: "w100" %>
            <% else %>
              <input type="datetime-local" name="topic[intdate1]" id="topic_intdate1" value=<%= newcurentdate %>>
            <% end %>
          </p>
        </td>
      </tr>
    </table>
  </div>
  <div class="col-lg-6">
    <table class="borderdiv">
      <tr>
        <td><h4>Окончание показов:</h4></td>
      </tr>
      <tr>
        <td>
          <p>
            <%= form.datetime_local_field :intdate2, class: "w100" %>
          </p>
        </td>
      </tr>
    </table>
  </div>
</div>
<div class="row">
  <div class="col-lg-3">
    <table class="borderdiv">
      <tr>
        <td><h4>Время:</h4></td>
      </tr>
      <tr>
        <td>
          <h5>
            <%= form.time_field :timetask, class: "w100" %>
          </h5>
        </td>
      </tr>
    </table>
  </div>
  <div class="col-lg-3">
    <table class="borderdiv">
      <tr>
        <td><h4>Показы:</h4></td>
      </tr>
      <tr>
        <td><h5><%= form.select(:activ, [['Вкл.', "Вкл."], ['Выкл.', "Выкл."]]) %></td>
      </tr>
    </table>
  </div>
  <div class="col-lg-3">
    <table class="borderdiv">
      <tr>
        <td><h4>Случай&shy;ный поря&shy;док:</h4></td>
      </tr>
      <tr>
        <td><h5><%= form.select(:rand, [['Выкл.', "Выкл."], ['Вкл.', "Вкл."]]) %></h5></td>
      </tr>
    </table>
  </div>
  <div class="col-lg-3">
    <table class="borderdiv">
      <tr>
        <td><h4>Пароль:</h4></td>
      </tr>
      <tr>
        <td>
          <h5>
            <% if @topic.password %>
              <input name="topic[password]" id="topic_password" class = "w100" value=<%= @topic.password%>>
            <% else %>
              <%= form.password_field :password, class: "w100" %>
            <% end %>
          </h5>
        </td>
      </tr>
    </table>
  </div>
</div>
<p>
  <%= form.submit "Сохранить", class: "topic_button btn btn-primary" %>
</p>
<% end %>
  <%= link_to 'Назад', topic_path(id: @topic) %>
<% end %>

<script type="text/javascript">
  $( document ).on('turbolinks:load', function() {
    $("#topic_countquestions").on("change", function(){
      let element = $("#topic_countquestions").val();
      element = element * 1;
      let hid = $("#topic_sucquest").val();
      hid = hid * 1;
      if (element < hid) {
      $("#topic_sucquest").val(element);
      }
    });
    $("#topic_sucquest").on("change", function(){
      let el = $("#topic_sucquest").val();
      el = el * 1;
      let el2 = $("#topic_countquestions").val();
      el2 = el2 * 1;
      if (el > el2) {
      $("#topic_countquestions").val(el);
      }
    });
    $("#topic_intdate1").on("change", function(){
      let dataelement = $("#topic_intdate1").val();
      intdate1 = new Date(dataelement);
      let dataelement2 = $("#topic_intdate2").val();
      if (dataelement2) {
        intdate2 = new Date(dataelement2);
        if (intdate1 > intdate2) {
          $("#topic_intdate2").val(dataelement);
        }
      }
    });
    $("#topic_intdate2").on("change", function(){
      let datael = $("#topic_intdate2").val();
      int1 = new Date(datael);
      let datael2 = $("#topic_intdate1").val();
      if (datael) {
        int2 = new Date(datael2);
        if (int1 < int2) {
          $("#topic_intdate1").val(datael);
        }
      }
    });
  });
</script>

app/views/topics/index.html.erb
<% if (user_signed_in?) and !(username_signed_in?) %>
  <div class="div-line"><h1>Задания</h1> <a href="<%= new_topic_path %>"><i class="fa fa-plus-circle fa-2x" aria-hidden="true"></i></a> </div>
  <% if (user_signed_in?) %><% idreg1 = current_user.id %><% end %>
  <% if Topic.find_by(idreg: idreg1) %>
    <table class ="task-tabl">
      <tr class="gl-zag-tabl">
        <th>Название</th>
        <th>Вопросов</th>
        <th>Проверить</th>
        <th>Настройки</th>
        <th>Удалить</th>
      </tr>
      <% @topics.each do |topic| %>
          <tr class="zag-tabl">
            <td><h4 class="div-line-small"><a href="/topics/<%= topic.id %>/questions"><%= topic.titletopic %></a></h4></td>
            <td><h4><%= topic.questions.count %></h4></td>
            <td><h4><a href="/topics/<%= topic.id %>/view"><i class="fa fa-pencil-square fa-1x" aria-hidden="true"></i></a></h4></td>
            <td><h4><a href="/topics/<%= topic.id %>"><i class="fa fa-cogs fa-1x" aria-hidden="true"></i></a></h4></td>
            <td><h4><a rel="nofollow" data-confirm="Удалить?" data-method="delete" href="/topics/<%= topic.id %>/"><i class="fa fa-trash-o" aria-hidden="true"></i></a></h4></td>
          </tr>
          <% unless Statisticscreator.find_by(idreg: idreg1) %>
            <% statistictest = [] %>
            <% statistictest[0] = topic.id %>
            <% Statisticscreator.create(test: statistictest, idreg: idreg1) %>
          <% else %>
            <% statistictest = Statisticscreator.find_by(idreg: idreg1).test %>
            <% unless statistictest.include?(topic.id) %>
              <% statistictest.push(topic.id) %>
              <% statistictest2 = statistictest.uniq %>
              <% stat = Statisticscreator.find_by(idreg: idreg1) %>
              <% stat.update(test: statistictest2) %>
            <% end %>
          <% end %>
        <% end %>
    </table>
    <%= paginate @topics %>

  <% end %>
<% end %>
<%= javascript_pack_tag 'topics_delete', 'data-turbolinks-track': 'reload' %>

app/views/topics/new.html.erb
<% if (user_signed_in?) %><% idreg1 = current_user.id %><% end %>
<% if (user_signed_in?) and !(username_signed_in?) %>
  <h1>Добавить тестовое задание</h1>
  <% curentdate = Time.new %>
  <% newcurentdate = curentdate.strftime("%Y-%m-%dT%H:%M") %>
  <%= form_with scope: :topic, url: topics_path, local: true do |form| %>
    <% if @topic.errors.any? %>
      <div id="error_explanation">
        <h2>
          <% er=@topic.errors.count %>
          <% if er>0 %>
            <span class="formerrors">Форма заполнена неправильно</span>
          <% end %>
        </h2>
      </div>
    <% end %>
    <div class="row form-group">
      <div class="col-sm-12">
        <%= form.label :title, "Название*" %><br>
        <% if @topic.errors[:titletopic].count > 0 %>
          <p class="formerrors">Ошибка заполнения</p>
          <ul>
            <li>Название тестового задания должно быть уникальным</li>
            <li>Минимальная длина поля 3 символа</li>
            <li>Максимальная длина поля 300 символов</li>
          </ul>
        <% end %>
        <%= form.text_field :titletopic, class: "w100", placeholder: "Ввидите уникальное название тестового задания" %>
        <small id="emailHelp" class="form-text text-muted">Обязательное поле для заполнения</small>
      </div>
    </div>
    <hr>
    <div class="row form-group">
      <div class="col-sm-4">
        <%= form.label :count, "Количество вопросов*" %><br>
        <input id="topic_countquestions" max="100" min="1" name="topic[countquestions]" step="1" type="number" value="10" class = "w100">
        <small id="emailHelp" class="form-text text-muted">Укажите количество вопросов в тесте</small>
      </div>
      <div class="col-sm-4">
        <%= form.label :answer_true, "Правильных ответов*" %><br>
        <input id="topic_sucquest" max="100" min="1" name="topic[sucquest]" step="1" type="number" value="5" class = "w100">
        <small id="emailHelp" class="form-text text-muted">Укажите количество правильных ответов для прохождения теста</small>
      </div>
      <div class="col-sm-4">
        <%= form.label :time, "Время*" %><br>
        <input type="time" name="topic[timetask]" id="topic_timetask" value="00:10" class = "w100">
        <small id="emailHelp" class="form-text text-muted">Укажите время для прохождения тестового задания</small>
      </div>
    </div>
    <hr>
    <div class="row form-group">
      <div class="col-sm-6">
        <%= form.label :start_view, "Начало показов*" %><br>
        <input type="datetime-local" name="topic[intdate1]" id="topic_intdate1" value=<%= newcurentdate %> class = "w100">
        <small id="emailHelp" class="form-text text-muted">Укажите дату запуска тестового задания</small>
      </div>
      <div class="col-sm-6">
        <%= form.label :finish_view, "Окончание показов" %><br>
        <%= form.datetime_local_field :intdate2, class: "w100" %>
        <small id="emailHelp" class="form-text text-muted">Дата окончания показов тестового задания</small>
      </div>
    </div>
    <hr>
    <div class="row form-group">
      <div class="col-sm-6">
        <%= form.label :success, "Успешное сообщение" %><br>
        <% if @topic.errors[:successmessage].count > 0 %>
          <p class="formerrors">Ошибка заполнения</p>
          <ul>
            <li>Минимальная длина поля 3 символа</li>
            <li>Максимальная длина поля 300 символов</li>
          </ul>
        <% end %>
        <%= form.text_area :successmessage, value: "Вы успешно прошли тест", class: "w100" %>
        <small id="emailHelp" class="form-text text-muted">Введите сообщение, которое будет показываться при успешном прохождении теста</small>
      </div>
      <div class="col-sm-6">
        <%= form.label :error, "Сообщение о неудаче" %><br>
        <% if @topic.errors[:failuremessage].count > 0 %>
          <p class="formerrors">Ошибка заполнения</p>
          <ul>
            <li>Минимальная длина поля 3 символа</li>
            <li>Максимальная длина поля 300 символов</li>
          </ul>
        <% end %>
        <%= form.text_area :failuremessage, value: "Вы не прошли тест", class: "w100" %>
        <small id="emailHelp" class="form-text text-muted">Введите сообщение, которое будет показываться при неудачном прохождении теста</small>
      </div>
    </div>
    <hr>
    <div class="row form-group">
      <div class="col-sm-4">
        <%= form.label :password, "Пароль" %><br>
        <% if @topic.errors[:password].count > 0 %>
          <p class="formerrors">Ошибка заполнения</p>
          <ul>
            <li>Минимальная длина поля 3 символа</li>
            <li>Максимальная длина поля 20 символов</li>
          </ul>
        <% end %>
        <%= form.password_field :password, class: "w100", placeholder: "Введите пароль (минимум: 3 символа)" %>
        <small id="emailHelp" class="form-text text-muted">Поле можно оставить пустым</small>
      </div>
      <% if (user_signed_in?) %><% idreg = current_user.id %>
        <%= form.hidden_field :idreg, value: idreg %>
        <%= form.hidden_field :codecreator, value: current_user.encrypted_password %>
      <% end %>
      <div class="col-sm-4">
        <%= form.label :view, "Показы*" %><br>
        <%= form.select(:activ, [['Вкл.', "Вкл."], ['Выкл.', "Выкл."]]) %>
        <small id="emailHelp" class="form-text text-muted">Настройте активность показов тестового задания</small>
      </div>
      <div class="col-sm-4">
        <%= form.label :rand, "Случайный порядок*" %><br>
        <%= form.select(:rand, [['Выкл.', "Выкл."], ['Вкл.', "Вкл."]]) %>
        <small id="emailHelp" class="form-text text-muted">Настройте порядок показов тестового задания</small>
      </div>
    </div>
    <hr>
      <p>
        <%= form.submit "Сохранить", class: "topic_button btn btn-primary" %>
      </p>
  <% end %>
  <%= link_to 'Тестовые задания', topics_path %>
<% end %>

<script type="text/javascript">
  $( document ).on('turbolinks:load', function() {
    $("#topic_countquestions").on("change", function(){
      let element = $("#topic_countquestions").val();
      element = element * 1;
      let hid = $("#topic_sucquest").val();
      hid = hid * 1;
      if (element < hid) {
      $("#topic_sucquest").val(element);
      }
    });
    $("#topic_sucquest").on("change", function(){
      let el = $("#topic_sucquest").val();
      el = el * 1;
      let el2 = $("#topic_countquestions").val();
      el2 = el2 * 1;
      if (el > el2) {
      $("#topic_countquestions").val(el);
      }
    });
    $("#topic_intdate1").on("change", function(){
      let dataelement = $("#topic_intdate1").val();
      intdate1 = new Date(dataelement);
      let dataelement2 = $("#topic_intdate2").val();
      if (dataelement2) {
        intdate2 = new Date(dataelement2);
        if (intdate1 > intdate2) {
          $("#topic_intdate2").val(dataelement);
        }
      }
    });
    $("#topic_intdate2").on("change", function(){
      let datael = $("#topic_intdate2").val();
      int1 = new Date(datael);
      let datael2 = $("#topic_intdate1").val();
      if (datael) {
        int2 = new Date(datael2);
        if (int1 < int2) {
          $("#topic_intdate1").val(datael);
        }
      }
    });
  });
</script>

app/views/topics/show.html.erb
<% if (user_signed_in?) %>
  <%= render "show_creator" %>
<% end %>

app/views/topics/view.html.erb
<h1><%= @topic.titletopic %>&nbsp;<a href="/topics/<%= @topic.id %>/questions/new"><i class="fa fa-plus-circle fa-1x" aria-hidden="true"></i></a></h1>
<hr>
<% count = 0 %>
<% if @topic.questions.count == 0 %>
<p>В задании нет вопросов.</p>
<% end %>
<% @topic.questions.order(id: :desc).each do |question| %>
  <% abcd = ["A:", "B:", "C:", "D:"] %>
  <div>
    <% img = question.imgquestion %>
    <% unless img.size.zero? %>
      <%= image_tag("#{img}", class: "question_img") %>
    <% end %>
    <h3>
      <%= count +=1 %>. <%= question.titlequestion %>
      <a href="/topics/<%= question.topic_id %>/questions/<%= question.id %>/edit"><i class="fa fa-cog fa-1x" aria-hidden="true"></i></a>
      <a data-confirm="Удалить?" rel="nofollow"data-method="delete" href="/topics/<%= question.topic_id %>/questions/<%= question.id %>"><i class="fa fa-trash" aria-hidden="true"></i></a>
    </h3>
    <% count_question = 0 %>
    <% answers = [question.answertrue, question.answer2, question.answer3, question.answer4] %>
    <% abcd.each do |answer_number|%>
      <% count_answers = answers.count - 1 %>
      <% num = rand(0..count_answers) %>
      <% if answers[num] == question.answertrue %>
        <h4 class="text-success"><%= abcd[count_question] %> <%= "#{answers[num]}" %><h4>
      <% else %>
        <h4 class="text-secondary"><%= abcd[count_question] %> <%= "#{answers[num]}" %><h4>
      <% end %>
      <% abcd -= [abcd[count_question]] %>
      <% answers -= [answers[num]] %>
    <% end %>
    <% count_question += 1 %>
    <br>
  </div>
  <% if count != @topic.questions.count %>
    <hr>
  <% end %>
  <br>
<% end %>
<%= link_to 'Назад', topics_path %>