config/routes.rb
Rails.application.routes.draw do
  get 'personaldata/index'
  get 'test_task/index'
  get 'profilevisitor/index'
  devise_for :usernames
  get 'profile', to: 'profile#index'
  get 'profilevisitor', to: 'profilevisitor#index'
  get 'test_task', to: 'test_task#index'
  get 'personaldata', to: 'personaldata#index'
  get 'links', to: 'links#index'


  resources :taskforms do
    resources :issues
    resources :youanswers
    resources :accepts
  end
  devise_for :users
  #resources :topics
  resources :visitors
  resources :statisticscreators
  resources :statisticvisitors
  resources :contacts
  resources :linktasks
  resources :topics do
    get :view, on: :member
    resources :questions
    resources :answers
    resources :consents
    resources :passwords
    resources :usertabls
    resources :settings
  end
  resources :creators
  get 'welcome/index'

  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/setting.rb
class Setting < ApplicationRecord
  belongs_to :topic
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :authenticate_user!
  before_action :topic_find
  before_action :setting_find, only: [:show, :edit, :update, :destroy]

  def index
    @setting = @topic.settings.all
  end

  def show
  end

  def new
    @setting = @topic.settings.new
  end

  def edit
  end

  def create
    @setting = @topic.settings.create(setting_params)
    redirect_to '/topics/'
  end

  def update
    if @setting.update(setting_params)
      render 'show'
    else
      render 'edit'
    end
  end

  def destroy
    @setting.destroy
    redirect_to '/topics/'
  end

  private

  def topic_find
    @topic = Topic.find(params[:topic_id])
  end

  def setting_find
    @setting = @topic.settings.find(params[:id])
  end

  def setting_params
    params.require(:setting).permit(:agebefore, :ageafter, :counttrue, :accomplishment, :sex, :country)
  end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/edit.html.erb
<h1>Настройки вывода статистики ответов "<%= @topic.titletopic %>"</h1>
<%= form_with model: @setting, url: topic_setting_path, local: true do |form| %>
  <div class="row">
    <div class="col-md-6">
      <table class="borderdiv">
        <tr>
          <td><h4>Воз&shy;раст от:</h4></td>
          <% if Setting.find_by(topic_id: @topic.id).agebefore %>
            <td><h5><input id="setting_agebefore" max="100" min="7" name="setting[agebefore]" step="1" type="number" value="<%= Setting.find_by(topic_id: @topic.id).agebefore %>" /></h5></td>
          <% else %>
            <td><h5><input id="setting_agebefore" max="100" min="7" name="setting[agebefore]" step="1" type="number" value="7" /></h5></td>
          <% end %>
        </tr>
      </table>
    </div>
    <div class="col-md-6">
      <table class="borderdiv">
        <tr>
          <td><h4>Воз&shy;раст до:</h4></td>
          <% if Setting.find_by(topic_id: @topic.id).ageafter %>
            <td><h5><input id="setting_ageafter" max="100" min="7" name="setting[ageafter]" step="1" type="number" value="<%= Setting.find_by(topic_id: @topic.id).ageafter %>" /></h5></td>
          <% else %>
            <td><h5><input id="setting_ageafter" max="100" min="7" name="setting[ageafter]" step="1" type="number" value="90" /></h5></td>
          <% end %>
        </tr>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <table class="borderdiv">
        <tr>
          <td><h4>Выпол&shy;не&shy;ние задания:</h4></td>
          <td><h5><%= form.select(:accomplishment, [['Все', "Все"], ['Да', "Да"], ['Нет', "Нет"]]) %></h5></td>
        </tr>
      </table>
    </div>
    <div class="col-md-4">
      <table class="borderdiv">
        <tr>
          <td><h4>Страна:</h4></td>
          <td><h5><%= form.select(:country, [['Все', "Все"], ['Россия', "Россия"], ['Беларусь', "Беларусь"], ['Украина', "Украина"], ['Армения', "Армения"], ['Грузия', "Грузия"], ['Азербайджан', "Азербайджан"], ['Узбекистан', "Узбекистан"], ['Киргизия', "Киргизия"], ['Израиль', "Израиль"], ['США', "США"]]) %></h5></td>
        </tr>
      </table>
    </div>
    <div class="col-md-4">
      <table class="borderdiv">
        <tr>
          <td><h4>Пол:</h4></td>
          <td><h5><%= form.select(:sex, [['Все', "Все"], ['Муж.', "Муж."], ['Жен.', "Жен."]]) %></h5></td>
        </tr>
      </table>
    </div>
  </div>
  <p>
    <%= form.submit "Сохранить", class: "topic_button btn btn-primary" %>
  </p>
<% end %>
<%= link_to 'Назад', topic_questions_path %>

app/views/settings/index.html.erb
<h1>Настройки вывода статистики ответов "<%= @topic.titletopic %>"</h1>
<div class="row">
  <div class="col-md-4">
    <table class="borderdiv">
      <tr>
        <td><h4>Воз&shy;раст от:</h4></td>
        <% if @setting.find_by(topic_id: @topic.id) %>
          <td><h4><%= @setting.find_by(topic_id: @topic.id).agebefore %></h4></td>
        <% end %>
      </tr>
    </table>
  </div>
  <div class="col-md-4">
    <table class="borderdiv">
      <tr>
        <td><h4>Воз&shy;раст до:</h4></td>
        <% if @setting.find_by(topic_id: @topic.id) %>
          <td><h4><%= @setting.find_by(topic_id: @topic.id).ageafter %></h4></td>
        <% end %>
      </tr>
    </table>
  </div>
  <div class="col-md-4">
    <table class="borderdiv">
      <tr>
        <td><h4>Выпол&shy;не&shy;ние задания:</h4></td>
        <% if @setting.find_by(topic_id: @topic.id) %>
          <td><h4><%= @setting.find_by(topic_id: @topic.id).accomplishment %></h4></td>
        <% end %>
      </tr>
    </table>
  </div>
</div>
<% if @setting.find_by(topic_id: @topic.id) %>
  <% idsettings = @topic.settings.find_by(topic_id: @topic.id).id  %>
  <a href="/topics/<%= @topic.id %>/settings/<%= idsettings %>/edit">Редактировать</a>
<% end %> |
<%= link_to 'Назад', topic_questions_path %>
<% #Setting.destroy_by(topic_id: @topic.id)%>

app/views/settings/new.html.erb
<% topicid = @topic.id %>
<% idreg = Topic.find_by(id: topicid).idreg %>
<% if (user_signed_in?) %><% idreg1 = current_user.id %><% end %>
  <% if idreg1 == idreg %>
    <% if @topic.settings.find_by(topic_id: topicid) == nil %>
      <h1>Настройки вывода статистики ответов</h1>
      <%= form_with(model: [ @topic, @topic.settings.build ], local: true) do |form| %>
      <p>
        <%= form.label :agebefore, "Возраст от" %><br>
        <input id="setting_agebefore" max="100" min="7" name="setting[agebefore]" step="1" type="number" value="7" />
      </p>
      <p>
        <%= form.label :ageafter, "Возраст до" %><br>
        <input id="setting_ageafter" max="100" min="7" name="setting[ageafter]" step="1" type="number" value="90" />
      </p>
      <p>
        <%= form.label :accomplishment, "Выполнение" %><br>
        <%= form.select(:accomplishment, [['Все', "Все"], ['Да', "Да"], ['Нет', "Нет"]]) %>
      </p>
      <p>
        <%= form.submit "Сохранить" %>
      </p>
    <% end %>
    <%= link_to 'Назад', topics_path %>
  <% else %>
    <% idsettings = @topic.settings.find_by(topic_id: @topic.id).id  %>
    <p>Параметры настроек для тестового задания "<%= @topic.titletopic %>" добавлены.</p>
    <a href="/topics/<%= @topic.id %>/settings/<%= idsettings %>/edit">Редактировать</a>
  <% end %>
<% end %>

app/views/settings/show.html.erb
<h1>Настройки вывода статистики ответов "<%= @topic.titletopic %>"</h1>
<div class="row">
  <div class="col-md-6">
    <table class="borderdiv">
      <tr>
        <td><h4>Воз&shy;раст от:</h4></td>
        <% if Setting.find_by(topic_id: @topic.id) %>
          <td>
            <h4>
              <a href="/topics/<%= @topic.id %>/settings/<%= @topic.settings.find_by(topic_id: @topic.id).id %>/edit"><%= Setting.find_by(topic_id: @topic.id).agebefore %></a>
            </h4>
          </td>
        <% end %>
      </tr>
    </table>
  </div>
  <div class="col-md-6">
    <table class="borderdiv">
      <tr>
        <td><h4>Воз&shy;раст до:</h4></td>
        <% if Setting.find_by(topic_id: @topic.id) %>
          <td>
            <h4>
              <a href="/topics/<%= @topic.id %>/settings/<%= @topic.settings.find_by(topic_id: @topic.id).id %>/edit"><%= Setting.find_by(topic_id: @topic.id).ageafter %></a>
            </h4>
          </td>
        <% end %>
      </tr>
    </table>
  </div>
</div>
<div class="row">
  <div class="col-md-4">
    <table class="borderdiv">
      <tr>
          <td><h4>Выпол&shy;не&shy;ние задания:</h4></td>
          <% if Setting.find_by(topic_id: @topic.id) %>
            <td>
              <h4>
                <a href="/topics/<%= @topic.id %>/settings/<%= @topic.settings.find_by(topic_id: @topic.id).id %>/edit"><%= Setting.find_by(topic_id: @topic.id).accomplishment %></a>
              </h4>
            </td>
          <% end %>
      </tr>
    </table>
  </div>
  <div class="col-md-4">
    <table class="borderdiv">
      <tr>
          <td><h4>Страна:</h4></td>
          <% if Setting.find_by(topic_id: @topic.id) %>
            <td>
              <h4>
                <a href="/topics/<%= @topic.id %>/settings/<%= @topic.settings.find_by(topic_id: @topic.id).id %>/edit"><%= Setting.find_by(topic_id: @topic.id).country %></a>
              </h4>
            </td>
          <% end %>
      </tr>
  </table>
</div>
  <div class="col-md-4">
    <table class="borderdiv">
    <tr>
        <td><h4>Пол:</h4></td>
        <% if Setting.find_by(topic_id: @topic.id) %>
        <td>
          <h4>
            <a href="/topics/<%= @topic.id %>/settings/<%= @topic.settings.find_by(topic_id: @topic.id).id %>/edit"><%= Setting.find_by(topic_id: @topic.id).sex %></a>
          </h4>
        </td>
        <% end %>
    </tr>
  </table>
  </div>
</div>
<% if Setting.find_by(topic_id: @topic.id) %>
  <% idsettings = @topic.settings.find_by(topic_id: @topic.id).id  %>
  <a href="/topics/<%= @topic.id %>/settings/<%= idsettings %>/edit">Редактировать</a>
<% end %> |
<%= link_to 'Назад', topic_questions_path %>