config/routes.rb
Rails.application.routes.draw do
  get 'personaldata/index'
  get 'test_task/index'
  get 'profilevisitor/index'
  devise_for :usernames
  get 'profile', to: 'profile#index'
  get 'profilevisitor', to: 'profilevisitor#index'
  get 'test_task', to: 'test_task#index'
  get 'personaldata', to: 'personaldata#index'
  get 'links', to: 'links#index'


  resources :taskforms do
    resources :issues
    resources :youanswers
    resources :accepts
  end
  devise_for :users
  #resources :topics
  resources :visitors
  resources :statisticscreators
  resources :statisticvisitors
  resources :contacts
  resources :linktasks
  resources :topics do
    get :view, on: :member
    resources :questions
    resources :answers
    resources :consents
    resources :passwords
    resources :usertabls
    resources :settings
  end
  resources :creators
  get 'welcome/index'

  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/creator.rb
class Creator < ApplicationRecord
  validates :photocreator, file_size: { less_than: 1.megabytes }
  mount_uploader :photocreator, ImageUploader
  validates :namecreator, length: { in: 2..25 }, format: { with: /\A[А-Я][а-яё]+\z/}, presence: true, if: :user_validation?
  validates :surnamecreator, length: { in: 3..25 }, format: { with: /\A[А-Я][а-яё]+\z/}, presence: true
  validates :telephonecreator, length: { in: 3..25 }, format: { with: /\A[0-9\s+-]+\z/}, presence: true
  validates :companycreator, length: { in: 3..300 }, allow_blank: true
  validates :promocodecreator, length: { in: 3..300 }, allow_blank: true

  private
  def user_validation?
    if User.find_by(id: self.idreg)
      if User.find_by(id: self.idreg).encrypted_password != self.codecreator
        errors.add(:idreg, "Ошибка")
      end
    else
      errors.add(:idcreator, "Ошибка")
    end

    if User.find_by(encrypted_password: self.codecreator)
      if User.find_by(encrypted_password: self.codecreator).id != self.idreg
        errors.add(:idreg, "Ошибка")
      end
    else
      errors.add(:idreg, "Ошибка")
    end
  end
end

app/controllers/creators_controller.rb
class CreatorsController < ApplicationController
  before_action :authenticate_user!
  before_action :creator_find, only: [:show, :edit, :update, :destroy]
  after_action :creator_delete, only: [:edit]

  def index
    @creators  = Creator.all
    redirect_to '/creators/new'
  end

  def show
    redirect_to '/profile/'
  end

  def new
    @creator = Creator.new
  end

  def edit
  end

  def create
    @creator = Creator.new(creator_params)

    if @creator.save
      redirect_to @creator
    else
      render 'new'
    end
  end

  def update
    if @creator.update(creator_params)
      redirect_to '/profile/'
    else
      render 'edit'
    end
  end

def destroy
  @creator.destroy
  redirect_to '/topics/'
end

  private

  def creator_find
    @creator = Creator.find(params[:id])
  end

  def creator_delete
    val = ["surnamecreator", "namecreator", "telephonecreator", "company", "promocode"]
    val.each do |value|
      $creator.del value + current_user.id.to_s
    end
  end

  def creator_params
    params.require(:creator).permit(:namecreator, :surnamecreator, :telephonecreator, :emailcreator,
        :photocreator, :companycreator, :promocodecreator, :idreg, :codecreator)
  end
end

app/helpers/creators_helper.rb
module CreatorsHelper
end

app/views/creators/edit.html.erb
<div class="container">
<h1>Редактировать личные данные</h1>
<%= form_with model: @creator, url: creator_path, local: true do |form|  %>
  <% if @creator.errors.any? %>
    <div id="error_explanation">
      <h2>
        <% er=@creator.errors.count %>
        <% if er>0 %>
        <span class="formerrors">Форма заполнена неправильно</span>
        <% end %>
      </h2>
      <% if @creator.errors[:photocreator] %>
        <p>Проверьте загружаемое изображение, размер файла не должен быть больше 1 Мб. Для загрузки используйте изображения в фомате .png, .jpg и .gif. </p>
      <% end %>
    </div>
  <% end %>
    <%= image_tag @creator.photocreator.url(:thumb), class: "photoprofile" if @creator.photocreator?%>
    <p class="inputphotocreator"><%= form.file_field :photocreator %></p>
    <hr>
    <div class="row">
      <div class="form-group col-lg-6 col-sm-12">
        <%= form.label :name, "Имя" %><br><%= form.text_field :namecreator, class: "w100" %>
      </div>
      <div class="form-group col-lg-6 col-sm-12">
        <%= form.label :surname, "Фамилия" %><br><%= form.text_field :surnamecreator, class: "w100" %>
      </div>
    </div>
    <hr>
    <div class="row">
      <div class="form-group col-lg-4 col-sm-12">
        <%= form.label :telephone, "Телефон" %><br><%= form.text_field :telephonecreator, class: "w100" %>
      </div>
      <div class="form-group col-lg-4 col-sm-12">
        <%= form.label :company, "Компания" %><br><%= form.text_field :companycreator, class: "w100" %>
      </div>
      <div class="form-group col-lg-4 col-sm-12">
        <%= form.label :promocode, "Промокод" %><br><%= form.text_field :promocodecreator, class: "w100" %>
      </div>
    </div>
    <hr>
    <%= form.hidden_field :idreg, id: "creator_idreg", value: current_user.id %>
    <%= form.hidden_field :codecreator, value: current_user.encrypted_password %>
    <p><%= form.submit "Сохранить", class: "topic_button btn btn-primary" %></p>
<% end %>
<p><a href="/profile">Назад</a></p>
</div>
<% rr = Dir.children("public/uploads/tmp/")%>
<% contrr = rr.count %>
<% contrr = (contrr-1)%>
<% for i in 0..contrr %>
<% x = Dir.children("public/uploads/tmp/#{rr[i]}")%>
<% x.each do |name| %>
  <% File.delete("public/uploads/tmp/#{rr[i]}/#{name}") %>
<% end %>
<% end %>
<% rr.each do |namef| %>
  <% if Dir.empty?("public/uploads/tmp/#{namef}")%>
    <% Dir.delete("public/uploads/tmp/#{namef}") %>
  <% end %>
<% end %>

app/views/creators/index.html.erb
<% @creators.each do |c| %>
  <% if c.photocreator !="" %>
    <img src="<%= c.photocreator %>">
  <% end %>
  <p><%= c.namecreator %></p>
  <p><%= c.surnamecreator %></p>
  <p><%= c.telephonecreator %></p>
  <p><%= c.companycreator %></p>
  <p><%= c.promocodecreator %></p>
  <p><%= c.idreg %></p>
  <hr>
<% end %>

app/views/creators/new.html.erb
<% if (user_signed_in?) %><% userid = current_user.id %>
  <% if Creator.exists? %>
    <% if Creator.find_by(idreg: userid) %>
      <h2><%= Creator.find_by(idreg: userid).namecreator %>, вы уже добавили данные</h2>
      <p>Для просмотра информации нажмите вкладку "Профиль".</p>
    <% else %>
      <h1>Добавить личные данные</h1>
      <% if @creator.errors.any? %>
        <div id="error_explanation">
          <h2>
            <% er = @creator.errors.count %>
            <% if er > 0 %>
              <span class="formerrors">Форма заполнена неправильно</span>
            <% end %>
          </h2>
        </div>
      <% end %>
      <div class="formswrapper">
        <%= form_with scope: :creator, html: { multipart:  true }, url: creators_path, local: true do |form| %>
        <div class="row">
          <div class="form-group col-lg-4 col-sm-12">
            <%= form.label :photo, "Аватарка" %><br><%= form.file_field :photocreator %>
          </div>
          <div class="form-group col-lg-4 col-sm-12">
            <%= form.label :name, "Имя*" %><br><%= form.text_field :namecreator, class: "w100" %>
          </div>
          <div class="form-group col-lg-4 col-sm-12">
            <%= form.label :surname, "Фамилия*" %><br><%= form.text_field :surnamecreator, class: "w100" %>
          </div>
        </div>
        <hr>
        <div class="row">
          <div class="form-group col-lg-4 col-sm-12">
            <%= form.label :telephone, "Телефон*" %><br><%= form.text_field :telephonecreator, class: "w100" %>
            <small class="form-text text-muted">Пример: +7 900-000-00-00</small>
          </div>
          <div class="form-group col-lg-4 col-sm-12">
            <%= form.label :company, "Компания" %><br><%= form.text_field :companycreator, class: "w100" %>
          </div>
          <div class="form-group col-lg-4 col-sm-12">
          <%= form.label :promocode, "Промокод" %><br><%= form.text_field :promocodecreator, class: "w100" %>
          </div>
        </div>
        <hr>
          <%= form.hidden_field :idreg, id: "creator_idreg", value: current_user.id %>
          <%= form.hidden_field :codecreator, value: current_user.encrypted_password %>
          <p><%= form.submit "Сохранить", class: "topic_button btn btn-primary" %></p>
        <% end %>
      </div>
      <div class="notation">
        <p>Все поля с пометкой (*) должны быть заполнены.</p>
        <p>Предоставляя свои персональные данные Пользователь даёт согласие на обработку, хранение и использование своих персональных данных. <%= link_to "Подробнее", personaldata_path %></p>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/creators/show.html.erb
<div class="container">
  <% if (user_signed_in?) %><% userid = current_user.id %><% end %>
    <% if Creator.find_by(idreg: userid) !="" %>
      <h1>Профиль пользователя</h1>
      <%= image_tag @creator.photocreator.url(:thumb), class: "photoprofile" if @creator.photocreator?%>
      <h4><%= @creator.surnamecreator %> <%= @creator.namecreator %> (<%= @creator.telephonecreator %>)</h4>
      <p><strong>Email: </strong><% if (user_signed_in?) %><%= current_user.email %><% end %></p>
      <p><strong>Id пользователя: </strong><% if (user_signed_in?) %><%= current_user.id %><% end %></p>
      <p><strong>Зарегистрирован:</strong><% if (user_signed_in?) %><% regdata = current_user.created_at %><%= regdata.time.strftime("%d-%m-%Y") %><% end %></p>
      <% if @creator.companycreator !="" %>
        <p><strong>Название организации:</strong><%= @creator.companycreator %></p>
      <% end %>
      <% if @creator.promocodecreator !="" %>
        <p><strong>Промокод:</strong><%= @creator.promocodecreator %></p>
      <% end %>
    <% end %>
  <p><a href="/creators/<%= Creator.find_by(idreg: userid).id %>/edit">Редактировать</a></p>
</div>